tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

#Brews

brew 'archey'
brew 'asciinema'
brew 'asciiquarium'
brew 'cowsay'
brew 'direnv'
brew 'elixir'
brew 'exa'
brew 'fortune'
brew 'git'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'neovim'
brew 'platformio'
brew 'rbenv'
brew 'ripgrep'
brew 'ruby-build'
brew 'sl'
brew 'thefuck'
brew 'wget'
brew 'zsh'

#Casks

cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-file-transfer'
cask 'appcleaner'
cask 'calibre'
cask 'discord'
cask 'enpass'
cask 'firefox'
cask 'flux'
cask 'font-fira-code'
cask 'fritzing'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-play-music-desktop-player'
cask 'iterm2-beta'
cask 'minecraft'
cask 'openemu'
cask 'openttd'
cask 'postman'
cask 'skype'
cask 'steam'
cask 'the-unarchiver'
cask 'transmission'
cask 'typora'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'xld'
