tap 'caskroom/cask'
tap 'caskroom/versions'
tap 'neovim/neovim'

#Brews

brew 'archey'
brew 'asciinema'
brew 'asciiquarium'
brew 'cowsay'
brew 'direnv'
brew 'elixir'
brew 'fortune'
brew 'git'
brew 'hub'
brew 'jq'
brew 'mas'
brew 'neovim/neovim/neovim'
brew 'platformio'
brew 'rbenv'
brew 'ripgrep'
brew 'ruby-build'
brew 'sl'
brew 'thefuck'
brew 'wget'
brew 'zsh'

#Casks

cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-file-transfer'
cask 'appcleaner'
cask 'discord'
cask 'enpass'
cask 'filezilla'
cask 'firefox'
cask 'flux'
cask 'fritzing'
cask 'google-chrome'
cask 'google-drive'
cask 'google-hangouts'
cask 'google-play-music-desktop-player'
cask 'iterm2-beta'
cask 'minecraft'
cask 'openemu'
cask 'openttd'
cask 'postman'
cask 'resilio-sync'
cask 'sequel-pro'
cask 'skype'
cask 'slack-beta'
cask 'steam'
cask 'sublime-text'
cask 'the-unarchiver'
cask 'transmission'
cask 'typora'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'
cask 'xld'
