systemctl --user import-environment DISPLAY
exec i3

# Speedy key-repeat rate 💨
xset r rate 200 100

# Load nvidia settings if they exist
[[ -f ~/.nvidia-settings-rc ]] && nvidia-settings --load-config-only
