systemctl --user import-environment DISPLAY

# Bind Caps lock to be Ctrl
setxkbmap -option caps:ctrl_modifier

# Load nvidia settings if they exist
[[ -f ~/.nvidia-settings-rc ]] && nvidia-settings --load-config-only

exec i3
