# Configuration file for Geoclue
#
# NOTE: All configurations settings below are mandatory and the defaults are
#       what you see before you edit them. If you want to keep the default
#       values around, copy and comment out the appropriate line(s) before
#       changing them.

# Agent configuration options
[agent]

# Whitelist of desktop IDs (without .desktop part) of all agents we recognise,
# separated by a ';'.
whitelist=geoclue-demo-agent;gnome-shell;io.elementary.desktop.agent-geoclue2;sm.puri.Phosh;lipstick;gammastep

# IP source configuration options
[ip]

# Enable the GeoIP source
enable=true

# Method (backend) to use for IP location. Currently implemented are:
# 'ichnaea': Use the Ichnaea (MLS) API with the URL from the wifi source.
# 'gmaps': Use the location determined by Google Maps.
# 'reallyfreegeoip': reallyfreegeoip.org. Fixed accuracy, see accuracy option below.
method=ichnaea

url=http://127.0.0.1:58573/

[network-nmea]
enable=false

[3g]
enable=false

[cdma]
enable=false

[modem-gps]
enable=false

[wifi]
enable=false
submit-data=false
submission-nick=geoclue

[compass]
enable=true

[static-source]
enable=false

# Application configuration options
#
# NOTE: Having an entry here for an application with allowed=true means that
#       geoclue will not ask agent to authorize the application. This is to
#       ensure that applications with built-in authorization mechanism (e.g web
#       browsers) do not have to be bound to agents.
#
#       If your application is denied access to location information and your
#       operating system doesn't provide any mechanism to change that, it is
#       likely a bug in your operation system (or geoclue). The solution is to
#       report the issue with all details, rather than adding your application
#       to this list.
#
# Format:
#
# # Desktop ID of application without .desktop part
# [random-app]
#
# # Allowed access to location information?
# allowed=true|false
#
# # Is application a system component?
# system=true|false
#
# # List of UIDs of all users for which this application is allowed location
# # info access, separate by ';'. Keep it empty for allowing it for all users.
# users=

[gnome-datetime-panel]
allowed=true
system=true
users=

[gnome-color-panel]
allowed=true
system=true
users=

[org.gnome.Shell]
allowed=true
system=true
users=

[io.elementary.desktop.agent-geoclue2]
allowed=true
system=true
users=

[sm.puri.Phosh]
allowed=true
system=true
users=

[epiphany]
allowed=true
system=false
users=

[firefox]
allowed=true
system=false
users=

[lipstick]
allowed=true
system=true
users=

[gammastep]
allowed=true
system=false
users=
