[helpers]

[gui.files]
"config/xinitrc" = "~/.xinitrc"
"config/Xresources" = "~/.Xresources"
"config/i3/config.i3config" = "~/.config/i3/config"
"config/i3status-rust/config.toml" = "~/.config/i3status-rust/config.toml"
"config/rofi/config.rasi" = "~/.config/rofi/config.rasi"

[alacritty.files]
"config/alacritty/config.yml" = "~/.config/alacritty/alacritty.yml"

[fd.files]
"config/fdignore" = "~/.fdignore"
