#!/bin/bash
#
# Run this one after you've got an OS installed, and you're logged in as a user
#

localectl set-locale LANG=en_AU.UTF-8
export LANG=en_AU.UTF-8
sudo pacman -S --noconfirm base-devel jq ansible

# libc++ and Spotify
gpg --keyserver hkp://keyserver.ubuntu.com:80 --receive-keys A2C794A986419D8A 7A3A762FAFD4A51F

#
# Aura
#
git clone https://aur.archlinux.org/aura-bin.git /tmp/aura-bin
cd /tmp/aura-bin
makepkg
sudo pacman -U --noconfirm /tmp/aura-bin/*.pkg.tar.zst
cd -

ansible-playbook ansible/playbook.yml -K

export PATH="$PATH:$HOME/.cargo/bin"

rustup install stable
rustup default stable

echo "Istalling AUR packages..."
sudo aura -Aa $(grep -v '^#' ~/.dotfiles/setup/aur)

eval "$(rtx activate bash)"
rtx completion fish >~/.config/fish/completions/rtx.fish

# NodeJS
echo "Istalling NodeJS..."
rtx install node@lts
rtx use --global node@lts

# Fresh
rm -f ~/.config/fish/config.fish
bash -c "$(curl -sL get.freshshell.com)"
rm -f ~/.freshrc
ln -s ~/.dotfiles/freshrc ~/.freshrc

echo "Done. Time to log out and in again!"
