#!/bin/bash
#
# Run this one after you've got an OS installed, and you're logged in as a user
#

localectl set-locale LANG=en_AU.UTF-8
export LANG=en_AU.UTF-8
sudo pacman -S --noconfirm base-devel jq ansible

#
# Paru
#
git clone https://aur.archlinux.org/paru-bin.git /tmp/paru-bin
cd /tmp/paru-bin
makepkg -si
cd -

ansible-playbook ansible/playbook.yml -K

export PATH="$PATH:$HOME/.cargo/bin"

rustup install stable
rustup default stable

echo "Istalling AUR packages..."
AUR_PACKAGES=$(grep -v '^#' ~/.dotfiles/setup/aur)
failed_aur_packages=()
for package in $AUR_PACKAGES; do
  paru -S --noconfirm "$package" || failed_aur_packages+=("$package")
done

eval "$(mise activate bash)"
mise completion fish >~/.config/fish/completions/mise.fish

# NodeJS
echo "Istalling NodeJS..."
mise install node@lts
mise use --global node@lts

echo "Installing dotfiles..."
echo 'packages = ["linux", "desktop"]' >~/.dotfiles/.dotter/local.toml
dotter

if [ ${#failed_aur_packages[@]} -ne 0 ]; then
  echo "The following AUR packages failed to install:"
  for pkg in "${failed_aur_packages[@]}"; do
    echo " - $pkg"
  done
fi

echo "Done. Time to log out and in again!"
