#!/bin/bash

#
# Here's where you begin for a brand new OS install :)
#

export INITIAL_SETUP=1
export GPG_KEY_ID="${GPG_KEY_ID:-DEF7E66A739ACB11}"

# Get version of latest release of a GitHub repository
github_release () {
  curl -s "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name'
}

export -f github_release

localectl set-locale LANG=en_AU.UTF-8
export LANG=en_AU.UTF-8

. setup/software.sh

zsh setup/finalize.zsh
