#!/bin/bash

#
# Here's where you begin for a brand new OS install :)
#

export INITIAL_SETUP=1

. setup/environment.sh

# Get version of latest release of a GitHub repository
github_release () {
  curl -s "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name'
}

export -f github_release

git clone "https://gitlab.com/ellsclytn/dotfiles.git" ~/.dotfiles
cd ~/.dotfiles

if [[ $OS == "arch" ]]; then
  localectl set-locale LANG=en_AU.UTF-8
  export LANG=en_AU.UTF-8
  ./setup/arch/setup.sh
fi

if [[ $OS == "ubuntu" ]]; then
  ./setup/ubuntu/setup.sh
fi

# Cross platform software
. setup/software.sh

zsh setup/finalize.zsh
